# Generated by Django 3.2.7 on 2021-10-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.IntegerField(choices=[(1, 'MESA 01'), (2, 'MESA 02'), (3, 'MESA 03'), (4, 'MESA 04'), (5, 'MESA 05')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(1, 'EM ANDAMENTO'), (2, 'PAGO'), (3, 'PRONTO')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='status',
            field=models.BooleanField(choices=[(0, 'Não'), (1, 'Sim')], verbose_name='Ativo'),
        ),
    ]
