# Generated by Django 3.2.7 on 2021-11-17 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0003_auto_20211028_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField(choices=[(1, 'MESA 01'), (2, 'MESA 02'), (3, 'MESA 03'), (4, 'MESA 04'), (5, 'MESA 05')])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='estoque',
            name='status',
            field=models.BooleanField(choices=[(0, 'Disponível'), (1, 'Indisponível')]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_pedido', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prato',
            name='status',
            field=models.BooleanField(choices=[(0, 'Disponível'), (1, 'Indisponível')]),
        ),
    ]
