# Generated by Django 3.2.7 on 2021-11-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20211117_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caixa',
        ),
    ]
