# Generated by Django 3.2.7 on 2021-11-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_delete_caixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField(choices=[(1, 'MESA 01'), (2, 'MESA 02'), (3, 'MESA 03'), (4, 'MESA 04'), (5, 'MESA 05')])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.IntegerField(choices=[(1, 'EM ANDAMENTO'), (2, 'PAGO'), (3, 'PRONTO')], default=0)),
                ('pagamento', models.IntegerField(choices=[(1, 'DINHEIRO'), (2, 'CARTÃO DÉBITO'), (3, 'CARTÃO CRÉDITO'), (4, 'PIX')], default=0)),
            ],
        ),
    ]
