# Generated by Django 3.2.7 on 2021-11-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_auto_20211117_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='mesa',
        ),
        migrations.AddField(
            model_name='caixa',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caixa_pedido', to='pedidos.pedido'),
            preserve_default=False,
        ),
    ]
