# Generated by Django 3.2.7 on 2021-11-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_auto_20211117_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista_mesas', models.CharField(choices=[(1, 'MESA 01'), (2, 'MESA 02'), (3, 'MESA 03'), (4, 'MESA 04'), (5, 'MESA 05')], default='1', max_length=20)),
            ],
        ),
    ]
