# Generated by Django 3.2.7 on 2021-11-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_mesas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mesas',
        ),
        migrations.AlterField(
            model_name='caixa',
            name='status',
            field=models.IntegerField(choices=[(1, 'EM ANDAMENTO'), (2, 'PRONTO')]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(1, 'EM ANDAMENTO'), (2, 'PRONTO')]),
        ),
    ]
