# Generated by Django 3.2.7 on 2021-11-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_auto_20211126_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='status',
            field=models.BooleanField(),
        ),
    ]
