# Generated by Django 3.2.7 on 2021-11-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_alter_caixa_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caixa_pedido', to='pedidos.pedido'),
        ),
    ]
